import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { v4 as uuidv4 } from "uuid";

import { trpc } from "../utils/trpc";
import { useState } from "react";

import UserUrls from "../components/UserUrls";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>("");

  const { data: sessionData } = useSession();

  const { mutate: addUrl } = trpc.urlShortener.generateUrl.useMutation();

  const handleNewShortLink = () => {
    addUrl({
      url,
      urlToRedirect: uuidv4(),
    });
    setUrl("");
  };

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container  flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h1 className="text-5x mb-12 font-extrabold tracking-tight text-white sm:text-[5rem]">
            URL <span className="text-[hsl(280,100%,70%)]">Short</span>ener
          </h1>
          <h2 className="text-xl text-white">Input your url here</h2>
          <input
            className="rounded bg-[hsl(280,100%,70%)] px-4 py-2 text-xl"
            type="text"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <div className="flex flex-col items-center gap-2">
            <p className="text-center text-2xl text-white">
              {sessionData && (
                <span>Logged in as {sessionData.user?.email}</span>
              )}
            </p>
            {!sessionData ? (
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => signIn()}
              >
                Sign in
              </button>
            ) : (
              <div className="flex items-center justify-center gap-4">
                <button
                  className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                  onClick={handleNewShortLink}
                >
                  Generate
                </button>
                <button
                  className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                  onClick={() => signOut()}
                >
                  Sign out
                </button>
              </div>
            )}
          </div>
          <UserUrls />
        </div>
      </main>
    </>
  );
};

export default Home;
