import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { v4 as uuidv4 } from "uuid";

import { trpc } from "../utils/trpc";
import { useState } from "react";
import UrlGeneratedModal from "../components/UrlGeneratedModal";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>("");
  const [isUrlGeneratedModalOpen, setIsUrlGeneratedModalOpen] = useState(false);

  const { data: sessionData } = useSession();

  const { mutate: addUrl } = trpc.urlShortener.generateUrl.useMutation();

  const handleNewShortLink = () => {
    addUrl({
      url,
      urlToRedirect: uuidv4(),
    });
    setIsUrlGeneratedModalOpen(true);
    setUrl("");
  };

  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UrlGeneratedModal
        isOpen={isUrlGeneratedModalOpen}
        setIsOpen={(isOpen) => setIsUrlGeneratedModalOpen(isOpen)}
      />
      {sessionData && (
        <>
          <h2 className="text-xl text-white">Input your url here</h2>
          <input
            className="rounded bg-[hsl(280,100%,70%)] px-4 py-2 text-xl"
            type="text"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <div className="flex flex-col items-center gap-2">
            <div className="flex items-center justify-center gap-4">
              <button
                className="rounded bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={handleNewShortLink}
              >
                Generate
              </button>
            </div>
          </div>
        </>
      )}
    </>
  );
};

export default Home;
